import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'

import styles from '../styles/Home.module.css';

import IntegrationIcon from '../assets/icons/integrationIcon.svg';
import CompassIcon from '../assets/icons/compassIcon.svg';
import MedalIcon from '../assets/icons/medalIcon.svg';

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Smart tracking | Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.home_container}>
        <div className={styles.home_content}>
          <div className={styles.home_content_text}>
            <span>
              Rastreie sua encomenda sem saber qual é a empresa responsável pela entrega.
            </span>
            <strong>
              Integramos com inúmeras plataformas, e você só se preocupa em fornecer o código de rastreio do seu pacote.
            </strong>
          </div>
          <div>
            asddadda
          </div>
        </div>
        <div className={styles.home_footer}>
          <div className={styles.home_footer_content}>
            <section>
              <IntegrationIcon
                title="Icone de Compasso"
              />
              <span>100+ Integrações</span>
              <strong>
                Integramos com inúmeras transportadoras, e estamossempre em busca de novas integrações.
              </strong>
            </section>
            <section>
              <CompassIcon
                title="Icone de Compasso"
              />
              <span>Preciso e exato</span>
              <strong>
                Rastreamos sua encomenda em tempo real, em total sincronismo com os dados da transportadora.
              </strong>
            </section>
            <section>
              <MedalIcon title="Icone de Compasso" />
              <span>Confiável</span>
              <strong>
                Retornamos dados reais e confiáveis, buscando diretamente na transportadora responsável pela entrega.
              </strong>
            </section>
          </div>
        </div>
      </main>
    </div>
  )
}

export default Home;
